### ISSUE TITLE
Catálogo de requisitos funcionales

### ISSUE THREAD

**Issue by alc1020** [alc1020/Tarea02#2]
Requisitos que tendrá que cumplir la aplicación.
1. Identificador único asignado.
2. Descripción formal de la función que realiza.

**Comment by Mse1003** [comment]
he subido el word del catalogo de requisitos, confirmarme que es el formato correcto y la informacion correcta y si no lo vuelvo a subir corregido. Gracias

**Comment by alc1020** [comment]
a mi me parece que está bien hecho. esperamos a que lo revise carmen, y lo cerramos si le parece adecuado
