### ISSUE TITLE
Especificación formal

### ISSUE THREAD

**Issue by alc1020** [alc1020/Tarea02#4]
Especificación de todos los casos identificados. Incluye:
1. Número identificador.
2. Precondiciones.
3. Secuencia normal.
4. Excepciones.
5. Poscondiciones (opc).
6. Rendimiento.
7. Frecuencia.
8. Importancia. 
9. Urgencia.
10. Comentarios (opc).

**Comment by CarmenRu** [comment]
Esta tarde subiré lo que tengo de momento de esta tarea

**Comment by Mse1003** [comment]
Carmen nos reunimos en la biblioteca para terminar este issue conjunto
